// turn {x: {val: 1, stiffness: 1, damping: 2}, y: 2} generated by
// `{x: spring(1, {stiffness: 1, damping: 2}), y: 2}` into {x: 1, y: 2}

import { Style, PlainStyle, OpaqueConfig } from './types';

export default function stripStyle(style: Style): PlainStyle {
  let ret: any = {};
  for (const key in style) {
    if (!Object.prototype.hasOwnProperty.call(style, key)) {
      continue;
    }
    ret[key] =
      typeof style[key] === 'number'
        ? style[key]
        : (style[key] as OpaqueConfig).val;
  }
  return ret;
}
